print("hello world")
print("This message")
print("is printed")
print("using VS Code IDE")
print("Johny Johny")
print("Yes Papa?")
print("Eating Sugar?")
#print("Yes Papa!")
print("No Papa!")
print("Telling lies?")
#print("Yes Papa!")
print("No, Papa!")
print("Open your Mouth")
print("Ah,ah,ah!")
name=input("Hey!What's your Name?")
print(name)

print("Mea Culpa"*3)